import { AgentDefinition } from "../types";

export const chatAgents: AgentDefinition[] = [
  {
    id: "general-chat",
    name: "General Chat Agent",
    description: "Versatile, articulate conversational agent for general inquiry, dialogue, and synthesis.",
    category: "chat",
    instructions: "Engage in helpful, nuanced, and precise conversation. Clarify ambiguity when needed.",
    capabilities: ["general_dialogue", "knowledge_synthesis", "answering_questions"],
    tools: ["web_search", "calculator"],
    supportedInputs: ["text", "image", "file"],
    supportedOutputs: ["text", "artifact"],
    preferredModels: ["gpt-4o", "claude-3-5-sonnet", "llama3"],
    permissions: ["READ"],
    enabled: true,
    avatarIcon: "MessageSquare",
  },
  {
    id: "writing-agent",
    name: "Writing Agent",
    description: "Crafts high-caliber prose, articles, scripts, documentation, and executive memos.",
    category: "chat",
    instructions: "Write compelling, coherent, and meticulously structured text tailored to the target audience and tone.",
    capabilities: ["prose_writing", "editing", "tone_adjustment", "creative_copy"],
    tools: ["document_parser"],
    supportedInputs: ["text", "file"],
    supportedOutputs: ["text", "artifact"],
    permissions: ["READ", "WRITE"],
    enabled: true,
    avatarIcon: "PenTool",
  },
  {
    id: "research-agent",
    name: "Research Agent",
    description: "Conducts systematic investigation, fact-checking, and deep-dive technical syntheses.",
    category: "chat",
    instructions: "Formulate research queries, cross-reference sources, analyze facts, and produce structured findings with citations.",
    capabilities: ["web_research", "fact_checking", "literature_review", "deep_dive"],
    tools: ["web_search", "web_browser", "document_parser"],
    supportedInputs: ["text", "file"],
    supportedOutputs: ["text", "artifact"],
    permissions: ["READ", "NETWORK"],
    enabled: true,
    avatarIcon: "Search",
  },
  {
    id: "summarization-agent",
    name: "Summarization Agent",
    description: "Distills complex multi-page documents, meetings, and transcripts into clear executive summaries.",
    category: "chat",
    instructions: "Identify core themes, extract actionable takeaways, maintain key quantitative figures, and eliminate fluff.",
    capabilities: ["summarization", "key_takeaways", "executive_briefs"],
    tools: ["document_parser"],
    supportedInputs: ["text", "file"],
    supportedOutputs: ["text", "artifact"],
    permissions: ["READ"],
    enabled: true,
    avatarIcon: "FileText",
  },
  {
    id: "translation-agent",
    name: "Translation Agent",
    description: "Fluent multi-lingual translator preserving cultural nuance, idioms, and technical vocabulary.",
    category: "chat",
    instructions: "Translate text faithfully while adapting idioms, tone, and grammar for native readability.",
    capabilities: ["translation", "localization", "language_identification"],
    tools: [],
    supportedInputs: ["text", "file"],
    supportedOutputs: ["text"],
    permissions: ["READ"],
    enabled: true,
    avatarIcon: "Globe",
  },
  {
    id: "explanation-agent",
    name: "Explanation Agent",
    description: "Breaks down intricate scientific, technical, or philosophical concepts for any level of comprehension.",
    category: "chat",
    instructions: "Use intuitive analogies, first-principles reasoning, and progressive disclosure.",
    capabilities: ["concept_breakdown", "analogies", "feynman_technique"],
    tools: ["calculator"],
    supportedInputs: ["text", "file"],
    supportedOutputs: ["text"],
    permissions: ["READ"],
    enabled: true,
    avatarIcon: "HelpCircle",
  },
  {
    id: "study-agent",
    name: "Study Agent",
    description: "Generates flashcards, practice quizzes, study guides, and pedagogical active-recall plans.",
    category: "chat",
    instructions: "Create spaced-repetition schedules, multiple-choice questions, and structured study modules.",
    capabilities: ["curriculum_design", "quiz_generation", "flashcards"],
    tools: ["document_parser"],
    supportedInputs: ["text", "file"],
    supportedOutputs: ["text", "artifact"],
    permissions: ["READ"],
    enabled: true,
    avatarIcon: "BookOpen",
  },
  {
    id: "brainstorming-agent",
    name: "Brainstorming Agent",
    description: "Divergent ideation engine for business concepts, project architectures, and creative pivots.",
    category: "chat",
    instructions: "Generate diverse, unconventional, high-impact ideas, then categorize and rank by feasibility and impact.",
    capabilities: ["divergent_thinking", "lateral_ideation", "scamper_method"],
    tools: [],
    supportedInputs: ["text"],
    supportedOutputs: ["text", "artifact"],
    permissions: ["READ"],
    enabled: true,
    avatarIcon: "Lightbulb",
  }
];
