import { AgentDefinition } from "../types";

export const codingAgents: AgentDefinition[] = [
  {
    id: "coding-agent",
    name: "Coding Agent",
    description: "Principal software engineer capable of scaffolding, modifying, and architecting fullstack codebases.",
    category: "coding",
    instructions: "Write production-ready, clean, idiomatic code. Follow architectural standards and maintain testability.",
    capabilities: ["code_generation", "scaffolding", "fullstack_development", "project_architecture"],
    tools: ["filesystem", "terminal", "code_runner", "git_tool"],
    supportedInputs: ["text", "code", "file"],
    supportedOutputs: ["code", "artifact", "text"],
    preferredModels: ["claude-3-5-sonnet", "gpt-4o"],
    permissions: ["READ", "WRITE", "EXECUTE", "FILES"],
    enabled: true,
    avatarIcon: "Code",
  },
  {
    id: "debugging-agent",
    name: "Debugging Agent",
    description: "Specialist in analyzing stack traces, root cause diagnostics, memory leaks, and logic faults.",
    category: "coding",
    instructions: "Analyze error logs, trace execution paths, isolate root causes, and propose minimal, high-confidence fixes.",
    capabilities: ["root_cause_analysis", "stacktrace_parsing", "logic_fix", "regression_prevention"],
    tools: ["filesystem", "terminal", "code_runner"],
    supportedInputs: ["text", "code", "file"],
    supportedOutputs: ["code", "text"],
    permissions: ["READ", "WRITE", "EXECUTE", "FILES"],
    enabled: true,
    avatarIcon: "Bug",
  },
  {
    id: "refactoring-agent",
    name: "Refactoring Agent",
    description: "Modernizes legacy code, improves performance, decouples modules, and elevates code health.",
    category: "coding",
    instructions: "Eliminate code smells, apply SOLID design patterns, reduce complexity, and preserve behavioral equivalence.",
    capabilities: ["code_refactoring", "decoupling", "optimization", "clean_code"],
    tools: ["filesystem", "code_runner"],
    supportedInputs: ["code", "file"],
    supportedOutputs: ["code", "artifact"],
    permissions: ["READ", "WRITE", "FILES"],
    enabled: true,
    avatarIcon: "RefreshCw",
  },
  {
    id: "code-review-agent",
    name: "Code Review Agent",
    description: "Strict automated reviewer evaluating security vulnerabilities, edge cases, performance, and best practices.",
    category: "coding",
    instructions: "Inspect diffs line-by-line. Flag OWASP security vulnerabilities, algorithmic bottlenecks, and style violations.",
    capabilities: ["code_review", "security_audit", "style_compliance", "performance_audit"],
    tools: ["filesystem"],
    supportedInputs: ["code", "file"],
    supportedOutputs: ["text", "artifact"],
    permissions: ["READ"],
    enabled: true,
    avatarIcon: "CheckSquare",
  },
  {
    id: "python-agent",
    name: "Python Agent",
    description: "Python expert specializing in scripts, backend APIs (FastAPI/Flask), data science, and automation.",
    category: "coding",
    instructions: "Write idiomatic Python 3 with type hints, PEP 8 standards, and optimal data structure choices.",
    capabilities: ["python_development", "data_science_scripts", "fastapi_backends", "asyncio"],
    tools: ["filesystem", "terminal", "code_runner"],
    supportedInputs: ["text", "code", "file"],
    supportedOutputs: ["code", "artifact", "text"],
    permissions: ["READ", "WRITE", "EXECUTE", "FILES"],
    enabled: true,
    avatarIcon: "Terminal",
  },
  {
    id: "typescript-agent",
    name: "TypeScript / JavaScript Agent",
    description: "Mastery in modern JavaScript/TypeScript, async runtimes, type gymnastics, and Node.js engines.",
    category: "coding",
    instructions: "Use strict types, avoid any, utilize modern ES features, and design robust interfaces.",
    capabilities: ["typescript_development", "nodejs_systems", "type_design"],
    tools: ["filesystem", "terminal", "code_runner"],
    supportedInputs: ["text", "code", "file"],
    supportedOutputs: ["code", "artifact", "text"],
    permissions: ["READ", "WRITE", "EXECUTE", "FILES"],
    enabled: true,
    avatarIcon: "Braces",
  },
  {
    id: "react-agent",
    name: "React & Next.js Agent",
    description: "Designs performant React components, Next.js App Router applications, hooks, and responsive UIs.",
    category: "coding",
    instructions: "Create modular, accessible UI components with Tailwind CSS, proper React state management, and SSR/SSG patterns.",
    capabilities: ["react_components", "nextjs_app_router", "tailwind_styling", "ui_architecture"],
    tools: ["filesystem", "code_runner"],
    supportedInputs: ["text", "code", "file"],
    supportedOutputs: ["code", "artifact", "text"],
    permissions: ["READ", "WRITE", "FILES"],
    enabled: true,
    avatarIcon: "Layout",
  },
  {
    id: "testing-agent",
    name: "Testing Agent",
    description: "Automates test suite generation: unit tests, integration tests, E2E specs, and edge case coverage.",
    category: "coding",
    instructions: "Generate robust test cases with comprehensive assertions, mocking, and boundary condition checks.",
    capabilities: ["unit_testing", "integration_testing", "test_automation", "mocking"],
    tools: ["filesystem", "terminal", "code_runner"],
    supportedInputs: ["code", "file"],
    supportedOutputs: ["code", "text"],
    permissions: ["READ", "WRITE", "EXECUTE", "FILES"],
    enabled: true,
    avatarIcon: "ShieldCheck",
  },
  {
    id: "git-agent",
    name: "Git & Version Control Agent",
    description: "Manages branch flows, creates semantic commits, handles merge conflicts, and prepares clean PRs.",
    category: "coding",
    instructions: "Generate conventional commits, manage branches, diffs, and inspect repository health safely.",
    capabilities: ["git_version_control", "commit_generation", "conflict_resolution", "branching"],
    tools: ["filesystem", "terminal"],
    supportedInputs: ["text", "code"],
    supportedOutputs: ["text", "code"],
    permissions: ["READ", "WRITE", "EXECUTE"],
    enabled: true,
    avatarIcon: "GitBranch",
  }
];
