import { AgentDefinition } from "../types";

export const creativeAgents: AgentDefinition[] = [
  {
    id: "image-prompt-agent",
    name: "Image Prompt Agent",
    description: "Crafts photorealistic, hyper-detailed Midjourney, DALL-E 3, and Flux generation prompts.",
    category: "creative",
    instructions: "Generate rich visual prompts with subject, lighting, camera angle, color grading, and lens specs.",
    capabilities: ["prompt_engineering", "visual_composition", "stylistic_direction"],
    tools: ["media_tool"],
    supportedInputs: ["text", "image"],
    supportedOutputs: ["text", "artifact"],
    permissions: ["READ"],
    enabled: true,
    avatarIcon: "Palette",
  },
  {
    id: "thumbnail-agent",
    name: "Thumbnail Design Agent",
    description: "Designs high-CTR YouTube and article thumbnail concepts with focal points, text overlays, and contrast.",
    category: "creative",
    instructions: "Create high-contrast thumbnail layouts that maximize click-through rate with clear focal emphasis.",
    capabilities: ["thumbnail_ideation", "ctr_optimization", "visual_contrast"],
    tools: ["media_tool"],
    supportedInputs: ["text"],
    supportedOutputs: ["text", "artifact", "image"],
    permissions: ["READ"],
    enabled: true,
    avatarIcon: "Image",
  },
  {
    id: "script-agent",
    name: "Script & Story Agent",
    description: "Writes engaging video scripts, narrative arcs, hooks, call-to-actions, and production outlines.",
    category: "creative",
    instructions: "Structure scripts with strong 3-second hooks, narrative tension, rhythmic pacing, and clear CTAs.",
    capabilities: ["scriptwriting", "storyboarding", "pacing_control", "hook_generation"],
    tools: [],
    supportedInputs: ["text"],
    supportedOutputs: ["text", "artifact"],
    permissions: ["READ"],
    enabled: true,
    avatarIcon: "Film",
  },
  {
    id: "design-agent",
    name: "UI / UX Design Agent",
    description: "Conceptualizes design systems, color palettes, wireframe layouts, and accessibility hierarchies.",
    category: "creative",
    instructions: "Establish coherent color tokens, typography scales, layout wireframes, and component hierarchies.",
    capabilities: ["design_systems", "color_theory", "wireframing", "ui_tokens"],
    tools: [],
    supportedInputs: ["text", "image"],
    supportedOutputs: ["text", "artifact", "code"],
    permissions: ["READ"],
    enabled: true,
    avatarIcon: "LayoutTemplate",
  }
];
