import { AgentDefinition } from "../types";

export const fileAgents: AgentDefinition[] = [
  {
    id: "pdf-agent",
    name: "PDF Agent",
    description: "Specialized reader and extractor for PDF documents, forms, research papers, and scanned text.",
    category: "file",
    instructions: "Extract text, tables, and sections from PDF files. Produce structured summaries and executive digests.",
    capabilities: ["pdf_parsing", "document_extraction", "table_recognition"],
    tools: ["document_parser", "filesystem"],
    supportedInputs: ["file"],
    supportedOutputs: ["text", "artifact"],
    permissions: ["READ", "FILES"],
    enabled: true,
    avatarIcon: "FileText",
  },
  {
    id: "spreadsheet-agent",
    name: "Spreadsheet & CSV Agent",
    description: "Analyzes CSV, XLSX, and tabular data, calculates statistics, and extracts trends.",
    category: "file",
    instructions: "Parse row/column data, compute statistical distributions, identify outliers, and output clean markdown tables.",
    capabilities: ["csv_analysis", "tabular_data", "data_aggregation", "formula_calculation"],
    tools: ["document_parser", "calculator"],
    supportedInputs: ["file", "text"],
    supportedOutputs: ["text", "artifact"],
    permissions: ["READ", "FILES"],
    enabled: true,
    avatarIcon: "Table",
  },
  {
    id: "json-agent",
    name: "JSON & Data Transform Agent",
    description: "Parses, transforms, validates schemas, and converts structured data across formats (JSON, YAML, CSV).",
    category: "file",
    instructions: "Validate JSON structures, write JSONPath queries, format data, and convert schema shapes.",
    capabilities: ["json_parsing", "schema_validation", "data_transformation"],
    tools: ["calculator", "filesystem"],
    supportedInputs: ["text", "file"],
    supportedOutputs: ["text", "code", "artifact"],
    permissions: ["READ", "FILES"],
    enabled: true,
    avatarIcon: "FileCode",
  },
  {
    id: "file-organizer",
    name: "File Organization Agent",
    description: "Scans directories, categorizes files by extension/topic, and suggests clean organizational structures.",
    category: "file",
    instructions: "Inspect file trees, propose clean directory structures, and generate safe batch reorganization plans.",
    capabilities: ["file_tree_inspection", "organization_planning", "batch_cleanup"],
    tools: ["filesystem"],
    supportedInputs: ["text"],
    supportedOutputs: ["text", "artifact"],
    permissions: ["READ", "FILES"],
    enabled: true,
    avatarIcon: "FolderTree",
  }
];
